### ISSUE TITLE
Possibility of overlaying two replays on top of each other

### ISSUE THREAD

**Issue by asdheyb** [TalicZealot/SotN-Replay-Player#3]
It would be particularly useful to add a second browse button to give users the ability to add a second replay so both can be seen at the same time. 
This could prove useful for analysing races in a tournament setting or when there has been a close finish, and also to learn how other players route seeds and what choices they make.
Different players would have differently coloured dots and leave different coloured trails for clarity and readablity.

**Comment by TalicZealot** [comment]
Two player replay playback has been added. Will continue to experiment with visuals and options.
